### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by ojoaopaulo** [Err0r-ICA/VARIOUS#1]
When I get the password on the telegram it says that the account doesn't exist anymore, could you send me the correct telegram link or password?

**Comment by AjiHack04** [comment]
Password?

**Comment by ojoaopaulo** [comment]
print

https://ibb.co/Yf4qR79

**Comment by AjiHack04** [comment]
Where password?

Pada tanggal Kam, 2 Jul 2020 19.31, jopakapui <notifications@github.com>
menulis:

**Comment by jopakapui** [comment]
That's what I want to know ... that telegram link doesn't work anymore
